### ISSUE TITLE
"verbatimLatitude": "Sherman trap"

### ISSUE THREAD

**Issue by MortenHofft** [gbif/model-tests#10]
The event table looks wrong it has `"verbatimLatitude": "Sherman trap"`
`habitat` also seem to be mapped to the wrong field

Aside from the wrong mapping it also seem to be missing fields (I do not know if it is on purpose of course)
`Verification Status` and `Collecting Source`

**Comment by tucotuco** [comment]
Column misalignment on one row in event.csv. Fixed in https://github.com/timrobertson100/model-tests/commit/a95bb20808b8723a5458989daaa762f386c391b8 and https://github.com/timrobertson100/model-tests/commit/f29f35e172897b9ca977720890abf0ef9596d5ee.
