### ISSUE TITLE
Lost event images

### ISSUE THREAD

**Issue by MortenHofft** [gbif/model-tests#11]
I'm trying to recreate https://arctos.database.museum/guid/DMNS:Mamm:11098

On that page there is a list (of 1) of events. And that Event has a list of images that is somehow linked to the "place".
For example digital entity 10207228
But I do not see how it is linked to anything. The model do not allow it to be linked to the event I think. And I do not see it linked in the entity_relationship table either

am I missing something?

**Comment by timrobertson100** [comment]
I'd have expected to go through the  `entity_event` join table for that, but I don't see that ID in there. Does that provide any hint though?

**Comment by timrobertson100** [comment]
That event is 10256356, which is only linked to material entities

Given the web page says "Media from the same Place." I suspect they are somehow linking the location to other events, and it is a digital entity from another collecting event we don't have in this export.

@tucotuco can please confirm that?

**Comment by tucotuco** [comment]
Arctos has the ability to link images to other types of entities than the types of material entities we track. In this case, images of the Location where the collecting event occurred. We have not modeled this capability to date.

**Comment by timrobertson100** [comment]
Closing this as an "out of scope" and it can be reopened if we feel it's super urgent. I suspect we'd need a clear case study that can demonstrate what scientific questions or important insight it adds.
