### ISSUE TITLE
No agent on images

### ISSUE THREAD

**Issue by MortenHofft** [gbif/model-tests#16]
@tucotuco I notice that Arctos have agents on their images
e.g. https://arctos.database.museum/media/10604439

I do not find it in the model - I assume it is left out on purpose but I just mention whatever I see missing relative to the Arctos page. It is really complete so far!

**Comment by tucotuco** [comment]
@MortenHofft Yes, they do have agents on their images. I asked and got a new export with those data in them. It affected the files entity_agent_role.csv and agent.csv. These were pushed in https://github.com/timrobertson100/model-tests/commit/9c6331b955496ef14283cdd9aee8e5d0ea67739f.
