### ISSUE TITLE
Duplicated identifiers

### ISSUE THREAD

**Issue by MortenHofft** [gbif/model-tests#19]
I'm trying to replicate  https://arctos.database.museum/guid/DMNS:Mamm:11098

I notice that the identifiers for the parasite relationship appears 2 places

I can ask for the identifiers for the entity `entityIdentifiersByEntityId`
But I can also ask for `entityRelationshipsBySubjectEntityId` and get the `externalObjectEntityId` value. Both will point me to e.g. `http://arctos.database.museum/guid/DMNS:Para:64`.

It looks to me like it shouldn't be in the identifiers table, but only in the relationsships
```
query {
  # the entity can have many IDs, so we need to ask for the entity through an entity identifiers table
  specimensIDs: allEntityIdentifiers(condition: {
    entityIdentifier: "https://arctos.database.museum/guid/DMNS:Mamm:11098"
  }) {
    # there should only be one entity with this ID
    nodes {
      entityId
      entityIdentifier
      entityIdentifierType
      specimen: entityByEntityId {
        entityId
        entityType
        
        # Identifiers section 
        # This is missing 2/5 columns: "relationsship" and "ID value" and "assignedBy" is missing. But might be inferred from the others?
        entityIdentifiersByEntityId {
          nodes {
            entityIdentifier
            entityIdentifierType
          }
        }
        # above identifiers include the parasites
        # I can also get to those via the related entities path like below
        entityRelationshipsBySubjectEntityId {
          nodes {
            externalObjectEntityId
          }
        }

      }
    }
  }
}
```

**Comment by tucotuco** [comment]
I'm not sure I understand the issue expressed here. The Identifiers table
should only represent relationships to self, whereas the
EntityRelationships would take care of relationships to other things.

**Comment by MortenHofft** [comment]
https://github.com/timrobertson100/model-tests/blob/c64965fc18b7c0df150133d44b97fbe4949d717e/arctos/files/entity_identifier.csv
line | entityID | entityIdentifier | entityIdentifierType
--|-- | -- | --
 4| 21714980 | https://arctos.database.museum/guid/DMNS:Mamm:11098 | Arctos object
  22|21714980 | http://arctos.database.museum/guid/DMNS:Para:664 | DMNS:Para

> The Identifiers table should only represent relationships to self

I'm not sure I get that. entity `21714980` has 2 identifiers that seem to point to different organisms? The types are different though, making me think that the type was intended to indicate the type of relationship (that one was a parasite of the other). But since that also appears in the relationship table it was confused https://github.com/timrobertson100/model-tests/blob/4a6ef6f4c9fe3e76238ae51fde985d7097427463/arctos/files/entity_relationship.csv

**Comment by timrobertson100** [comment]
Isn't this just a data mistake in the CSV, where http://arctos.database.museum/guid/DMNS:Para:664 is being added to the wrong entity?

**Comment by MortenHofft** [comment]
That is the question I'm posing yes.

> It looks to me like it shouldn't be in the identifiers table, but only in the relationsships

**Comment by tucotuco** [comment]
Those references to other entities are spurious here. The belong only in the EntityRelationship. Fixed with https://github.com/timrobertson100/model-tests/commit/37f212580606944a29b5c1da116eff4b88c5386e.
