### ISSUE TITLE
I miss a link between host and parasite

### ISSUE THREAD

**Issue by MortenHofft** [gbif/model-tests#21]
I'm looking at https://arctos.database.museum/guid/DMNS:Mamm:11098
and wonder how to recreate it. It would be nice to be able to link to the parasite. But I believe it isn't linked at the moment.

What I try to do is: go to the [relationships table](https://github.com/timrobertson100/model-tests/blob/37f212580606944a29b5c1da116eff4b88c5386e/arctos/files/entity_relationship.csv) 
and lookup my entity `21714980 ` and find this

entityRelationshipID | dependsOnEntityRelationshipID | subjectEntityID | entityRelationshipType | objectEntityID | externalObjectEntityID
-- | -- | -- | -- | -- | --
1 |   | 21714980 | host of |   | http://arctos.database.museum/guid/DMNS:Para:664
2 |   | 21714980 | host of |   | http://arctos.database.museum/guid/DMNS:Para:64
3 |   | 21714980 | host of |   | http://arctos.database.museum/guid/DMNS:Para:6

 But the `ObjectEntityID` isn't filled. 

I can go to the [identifiers table](https://github.com/timrobertson100/model-tests/blob/37f212580606944a29b5c1da116eff4b88c5386e/arctos/files/entity_identifier.csv#L5) and look up e.g.`http://arctos.database.museum/guid/DMNS:Para:664` and get the entityID `26462265`. But shouldn't it just be in relationships table to begin with?

**Comment by tucotuco** [comment]
Addressed by adding keys to objectedEntityID for objects with URIs in https://github.com/timrobertson100/model-tests/commit/7e68fb1614fbb6ddf8e9c265942f339a3a969478.
