### ISSUE TITLE
media as a "part"

### ISSUE THREAD

**Issue by MortenHofft** [gbif/model-tests#22]
@tucotuco I notice that media is handled as a `part` in the parka example. As well as a digital entity. Is this an oddity in the source data or should it be understood as if the image is a printed photograph that is handled as a museum object?

https://arctos.database.museum/guid/UAM:EH:UA67-133-0001

Media doesn't appear as a `part` in the chipmunk example.
https://arctos.database.museum/guid/DMNS:Mamm:11098

**Comment by Jegelewicz** [comment]
I'll chime in here. The media part should be understood as if the image is a printed photograph that is handled as a museum object. The media in the DMNS:Mamm record is digital only, so there is no part.

**Comment by tucotuco** [comment]
Thanks for covering this one @Jegelewicz.
