### ISSUE TITLE
Is parts museum objects?

### ISSUE THREAD

**Issue by MortenHofft** [gbif/model-tests#23]
Hi @tucotuco 
I was hoping you could help me understand something. 

On this page https://arctos.database.museum/guid/DMNS:Mamm:11098
there is a section called "Parts". I would have assumed that e.g. the skeleton had its own url entry in Arctos, catalog number, possibly images etc. But it seems to be sort of a dead end. But it is also modelled as a material entity similar to the organism.

This is somewhat related to my question in https://github.com/timrobertson100/model-tests/issues/22

So far my assumption have been that any material entity would be an entry in a material catalogue. With a url of its own. taxonomy, identifications, possible images etc. But I guess in this case the material kind of inherits its taxonomy and identifications from the "parent" entity. What are these parts? Are they simply stubs because they haven't beed digitized? Or are we misrepresenting them as material entities? Should it be handled with vocabularies?

I know this isn't a very precise question. I hope it is precise enough that you can understand my confusion.

Thanks

**Comment by tucotuco** [comment]
Hi @MortenHofft.  Parts are strictly children of cataloged items. They do not have independent catalog numbers. In Arctos, media are linked to cataloged items, not to parts. In the Unified Model, the DigitalEntity can be linked at either level - either the cataloged item (which is a Material Entity) or the part (which is also a MaterialEntity related to the cataloged item as "part of").

> So far my assumption have been that any material entity would be an entry in a material catalogue. 
I'm not sure what you mean by entry, but maybe what I said above explains it. They do not necessarily have independent catalog numbers. They may have GUIDs, or they may have only identifiers within the scope of the dataset. They can be the thing used in an Identification (they aren't in Arctos yet), but their parent cataloged item might be the Entity is linked instead. 

They are not stubs for sure. They have been digitized. They are most like dwc:preparations. They are correctly represented as MaterialEntities. The materialEntityType is the place for vocabularies for parts, and would consist of things like the terms in the Uberon anatomy ontology.

I hope that helps, but keep the questions coming.

**Comment by MortenHofft** [comment]
It does answer. Thank you. It just raise the next question for me - how to present this intuitively in a user interface if other map their data differently and attach catalogue numbers, images etc to the parts. But I will give it some thought. Thanks again
