### ISSUE TITLE
Remarks missing

### ISSUE THREAD

**Issue by MortenHofft** [gbif/model-tests#24]
@tucotuco looking at https://arctos.database.museum/guid/UAM:EH:UA67-133-0001 I see this block
> Remarks: Made by Aisana, the wife of Olaranna [formerly transcribed as Aulagana], the last chief of King Island.

But It isn't not in the CSVs. Is it deliberate or an oversight? It seems like useful/interesting information.

**Comment by tucotuco** [comment]
Those data are not in the csv files exported from Arctos. It will have to be ignored.
