### ISSUE TITLE
BioWide: Add confidence of taxonomic assignment

### ISSUE THREAD

**Issue by timrobertson100** [gbif/model-tests#30]
After discussion with John W. we propose to add this as an actual property of the SequenceTaxon rather than an assertion.
Our expectation is that when taxa are assigned to sequences, an algorithm will always be used that provides a numeric value about the "confidence" of the snap.

**Comment by tucotuco** [comment]
Done, see Figure 1 in the [use case document](https://docs.google.com/document/d/1-ykWOKuZiMEn6APLWv5Ea0ZtF3sxoeCLtK4EWX9tt84/edit#).
