### ISSUE TITLE
Decide policy on relationship identifiers

### ISSUE THREAD

**Issue by timrobertson100** [gbif/model-tests#9]
Currently `entity_relationship` mixes both local and external identifiers as described in https://github.com/timrobertson100/model-tests/issues/8. This is "by design" but this might warrant a redesign bearing in mind that:

1.  It prohibits the declaration of a foreign key. This in turn breaks any tool that relies on schema introspection to understand relationships (e.g. GraphQL tools on PG that we're using here)
2. It is not intuitive to developers given most other ids are local identifiers (higherGeographyID is one other unexpected example)
3. It will prove fragile since there are no guarantees for use (is it resolvable? what resolver to use?) and the schema of the object at the other end is unknown.

This may appear in other IDs in the model but will be particularly important for a table as fundamental as relationship as it defines how all entities relate.

To overcome 1. to allow for exploration we can make an additional field (e.g. `externalObjectEntityID`) to distinguish them

**Comment by tucotuco** [comment]
@timrobertson100 We seem to have a solution for this one in place. Can we close this issue?

**Comment by timrobertson100** [comment]
Yes, we'll alias on read if needed
